### ISSUE TITLE
Change sidebar toggle position

### ISSUE THREAD

**Issue by marcobambini** [jhildenbiddle/docsify-themeable#1]
Thanks for your excellent theme. I am using it for my gravity language documentation but so far I wasn't able to position the sidebar toggle on bottom left (like in the vue.css default theme). Any help would be really appreciated.

**Comment by jhildenbiddle** [comment]
Hi @marcobambini.

Changing the sidebar toggle position/behavior to match docsify's "Vue" theme isn't easily done with CSS custom properties, but you can always write your own custom CSS to override the docsify-themeable CSS.

Include this CSS  in a `<style>` tag after the theme `<link>`:

```css
.sidebar-toggle .sidebar-toggle-button {
    top: auto;
    bottom: 0;
    transition: transform var(--sidebar-transition-duration) ease-out;
}

body.close .sidebar-toggle .sidebar-toggle-button {
    transform: translate(calc(0px - var(--sidebar-width)));
}


@media (min-width: 48em) {
    .sidebar-toggle .sidebar-toggle-button {
        transform: translate(calc(0px - var(--sidebar-width)));
    }

    body.close .sidebar-toggle .sidebar-toggle-button {
        transform: translate(0);
    }
}
```

FWIW, the position of the sidebar toggle was changed for docisfy-themeable to address a handful of issues with docsify's "bottom-left" positioning. Specifically, the toggle is more discoverable, won't overlap sidebar content (when visible) or markdown content (when sidebar is hidden), and wont cause iOS's bottom-navigation bar to appear when tapped (thereby requiring two taps to actually toggle the sidebar).

Hope this helps.
