### ISSUE TITLE
Hovering over the sidebar, `.app-name` moves 5px

### ISSUE THREAD

**Issue by dunhamjared** [jhildenbiddle/docsify-themeable#22]
When you hover over the sidebar, `.app-name` moves 5px to the left.

Had to apply a custom css style for this not to happen:

```css
body:not([data-platform^="Mac"]) .sidebar:hover>*:not(.sidebar-nav){
    margin-right: 0;
}
```

Chrome Version 73.0.3683.103 (Official Build) (64-bit)
Using: https://cdn.jsdelivr.net/npm/docsify-themeable@0/dist/css/theme-simple-dark.css
