### ISSUE TITLE
PrismJS Not Working

### ISSUE THREAD

**Issue by poppabear8883** [jhildenbiddle/docsify-themeable#4]
They simply don't appear to be working as expected
```html
<link rel="stylesheet" href="https://unpkg.com/docsify-themeable/dist/css/theme-defaults.css">
```
```css
:root {
      --base-font-size: 16px;
      --code-font-size: 14px;
      /*--code-theme-text: #00a1df;*/
      --code-inline-color: #ff0bd3;
    }
```

```html
  <!-- Docsfiy Library -->
  <script src="//unpkg.com/docsify/lib/docsify.min.js"></script>

  <!-- Themeable Library -->
  <script src="//unpkg.com/docsify-themeable"></script>

  <!-- Plugins -->
  <script src="//unpkg.com/docsify/lib/plugins/search.min.js"></script>
  <script src="//unpkg.com/docsify-copy-code"></script>

  <!-- Syntax Highlighting -->
  <script src="//unpkg.com/prismjs/components/prism-php.min.js"></script>
  ...
```

**RESULTS:**
![image](https://user-images.githubusercontent.com/7263458/46364468-df85da80-c643-11e8-8d37-79ffdcd5fceb.png)
