### ISSUE TITLE
--sidebar-nav-strong-font-size is not styling navbar strong items.

### ISSUE THREAD

**Issue by trusktr** [jhildenbiddle/docsify-themeable#46]
I think the reason is that I'm using nested menu items, like this:

```md
-   **Guide**

    -   [Install](/install.md)
    -   [Workflows](/workflows.md)

-   **Examples**

    -   [Hello 3D](/examples/hello3d.md)
    -   [Hello 3D, Parent Transforms](/examples/hello3d-parent-transforms.md)
    -   [Ripple flip](/examples/ripple-flip.md)
    -   [Autolayout (declarative)](/examples/autolayout-declarative.md)
    -   [Autolayout (imperative)](/examples/autolayout-imperative.md)
    -   [Morphing spiral](/examples/spiral.md)
    -   [obj-model](/examples/obj-model.md)
    -   [Buttons with shadow](/examples/buttons-with-shadow.md)
    -   [material-texture](/examples/material-texture.md)
    -   [Origin](/examples/origin.md)

-   **API Reference**
    <!-- __API_AUTOGENERATED_BEGIN__ -->
  - components/
    - [Cube](/api/components/Cube.md)
  - core/
    - [ImperativeBase](/api/core/ImperativeBase.md)
    - [Node](/api/core/Node.md)
    - [TreeNode](/api/core/TreeNode.md)
  - html/
    - [WithUpdate](/api/html/WithUpdate.md)

<!-- __API_AUTOGENERATED_END__ -->
```

The following screenshot shows that, despite the item (highlighted as I have selected it in the element inspector) being in a `<strong>`, it does not have a `--sidebar-nav-strong-font-size` property:

![sidebar-strong](https://user-images.githubusercontent.com/297678/82111147-dd2ca300-96f7-11ea-8818-e32793de8724.png)

Setting `--sidebar-nav-strong-font-size: 100px;` doesn't have an effect.

**Comment by trusktr** [comment]
I believe this is because the selector is too reliant on the structure (something we should move away from in Docsify 5.0):

https://github.com/jhildenbiddle/docsify-themeable/blob/6cada9522411284bd30678aa4556f1bd390365de/src/scss/app/_sidebar.scss#L158-L169

**Comment by trusktr** [comment]
For 4.0, should that selector be modified to 

```scss
 ul > li,
 ul > li > p { 
     > span, 
     > strong { 
```

?

I'm not sure about that `span` yet though.

In my plain CSS of my site, I added this:

```css
.sidebar-nav ul > li > p > strong,
.sidebar nav ul > li > p > strong {
	display: block;
	margin: var(--sidebar-nav-strong-margin);
	padding: var(--sidebar-nav-strong-padding);
	border-width: var(--sidebar-nav-strong-border-width, 0);
	border-style: solid;
	border-color: var(--sidebar-nav-strong-border-color);
	color: var(--sidebar-nav-strong-color);
	font-size: var(--sidebar-nav-strong-font-size);
	font-weight: var(--sidebar-nav-strong-font-weight);
	text-transform: var(--sidebar-nav-strong-text-transform);
}
```

After placing that CSS I could then style my headers like in the design in the screenshot at https://github.com/jhildenbiddle/docsify-themeable/issues/48#issuecomment-629682451.
