### ISSUE TITLE
style variables for top-level navbar links

### ISSUE THREAD

**Issue by trusktr** [jhildenbiddle/docsify-themeable#51]
There don't appear to be any yet. I see variables that apply to nested ul/li elements (I suppose for the drop downs), but I don't see any variables being applied for styling the top-level navbar links.

Is this intentional, because it is easy enough to write selectors to target those? Or docsify-themeable should have it, but is still a ToDo item?

**Comment by jhildenbiddle** [comment]
It was intentional in that I didn't expect people to dramatically alter the navbar top-level links, but I'm sure if I were to revisit it now I may do things differently (it's been a while). The `--navbar-root-` and `--navbar-menu-root-` properties offer a [few options](https://jhildenbiddle.github.io/docsify-themeable/#/customization?id=navbar), but they're admittedly pretty basic.

For example:

```css
:root {
  /* Set top-level link background */
  --navbar-root-background: blue;
  /* Set top-level link text color */
  --navbar-root-color: green;
  /* Set top-level link-with-dropmenu background */
  --navbar-menu-root-background: purple;
}
```

The challenge with selecting theme options to make available is finding the right balance between too few to be useful and so many that it's overwhelming. My goal is to land somewhere the middle, allowing folks to make modified versions of the default themes that look new but are just 5, 10, or 20 property changes under the hood. If folks want something *radically* different, they may have to fall back to writing their own CSS as well.

What style changes were you hoping to make? This would help determine which new properties to add.
