### ISSUE TITLE
In the cover page Custom background is invalid

### ISSUE THREAD

**Issue by dmbcjl** [jhildenbiddle/docsify-themeable#82]
# Plan 1
Write the following code in `_coverpage.md`, a gray background will be displayed on the cover, and there will be no pictures
``` md
<!-- _coverpage.md -->

<!-- background image -->

![](_media/bg.png)
```
# Plan 2
Write the following code in `<style></style>`, the effect is similar to **Plan 1**, but there is still no picture
```css
:root {
    --cover-background-image: url('_media/bg.png');
}
```

>At first I thought it was caused by a plug-in, but then I directly built a brand new page, but the above error still occurred
