### ISSUE TITLE
guide for making docsify plugin themeable compatible

### ISSUE THREAD

**Issue by jthegedus** [jhildenbiddle/docsify-themeable#9]
Hi, cheers for your work!

I'm wanting to develop a few Docsify plugins and would like to know how to make them support multiple themes.

There aren't really any guides on making plugins, let alone themeable-compatible ones, so I'm just reading other peoples source code at this time.

Do you have any recommendations of which plugins I should be looking at for themeable compatibility? Also, do you plan on making any guides?

**Comment by jhildenbiddle** [comment]
Hi @jthegedus.

The docsify site offers a [Write a Plugin](https://docsify.js.org/#/write-a-plugin) page that lists all of the plugin hooks and a few examples. You can also check out the [plugins](https://github.com/jhildenbiddle/docsify-themeable/tree/master/src/js) in this repo for more examples. This will help you get acquainted with how docsify plugins are created.

With regards to making themes "themeable-compatible", I'm not sure if you mean "compatible with different themes" in a general sense (e.g. any docsify theme) or specifically "compatible with [docsify-themeable themes](https://jhildenbiddle.github.io/docsify-themeable/#/themes)". The former is only possible in the most basic scenarios because there are so few options, while the latter is exactly what docsify-themeable was created for. 

### Creating a plugin with general theme support

Let's say you're creating a plugin called "docsify-fancy-images" that automatically adds a colored border and border radius to all images. Your JavaScript would do something like find all images in the content area after each page load and add a "fancy-image" class to each one. If you created your plugin assuming every docsify site uses the [vue.css theme](https://docsify.js.org/#/themes), you might hard code the vue.css [theme color](https://docsify.js.org/#/configuration?id=themecolor) in your CSS to make the border color match:

```css
img.fancy-image {
  border-width: 2px;
  border-style: solid;
  border-color: #3F51B5; /* vue.css theme color */
  border-radius: 5px;
}
```

The problem is that docsify offers multiple [themes](https://docsify.js.org/#/themes) and the vue.css theme color defined in your CSS won't match other themes. Fortunately, docsify sets the theme color using [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*). This allows you to access this value from your CSS:

```css
img.fancy-image {
  border-width: 2px;
  border-style: solid;
  border-color: var(--theme-color); /* docsify */
  border-radius: 5px;
}
```

Now the border color will match whatever `--theme-color` is defined in the docsify configuration. Great!

Now let's do the same for the other properties...

Nope. Docsify provides only *one* CSS custom property (`--theme-color`) that you can access in your own CSS. This means that in order to use style values from the current theme you are limited to using 1) the text color via [`currentColor`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentColor_keyword), 2)  [rgba()](https://css-tricks.com/the-power-of-rgba/) to fake shades (darker) and tints (lighter), or 3) [getComputedStyle()](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) to get style values from exiting DOM elements. Depending on your plugin these options may be enough to have your styles work with most themes. If not...

### Creating a plugin with docsify-themeable support

Docsify-themeable was built with [customization](https://jhildenbiddle.github.io/docsify-themeable/#/customization) in mind. All "themeable" styles are defined using CSS custom properties and are the same across all docsify-themeable themes. This means you can review the [available theme properties](https://jhildenbiddle.github.io/docsify-themeable/#/customization?id=app) and use them in your own CSS:

```css
img.fancy-image {
  border-width: 2px;
  border-style: solid;
  border-color: var(--theme-color); /* docsify */
  border-radius: var(--border-radius-m, 5px); /* docsify-themeable, fallback */;
}
```

When using a docsify-themeable theme, both the border color and radius values will be adopted from the current theme. When using a standard docisfy theme, the border color will be adopted from the current theme and the radius value will use the `5px` fallback value since the `--border-radius` value does not exist.

What about the `border-width` value? 

Docsify-themeable doesn't have a default `--border-width` property that we can use so we're left with three options:

1. Leave it hard coded if we don't want to promote it as a "themeable" property. Users can still override your `2px` value, but they'll have to dig into your CSS to determine what class name your using and then write their own CSS to override it. Doable, but not exactly "themeable" since they're just hacking your CSS.

1. Find some other `--[something]-border-width` property to use as a default

   We can adopt the `<blockquote>` border width value from docsify-themeable if present, otherwise fallback to our previous `2px` value.

   ```css
   img.fancy-image {
     border-width: var(--blockquote-border-width, 2px);
     border-style: solid;
     border-color: var(--theme-color);
     border-radius: var(--border-radius-m, 5px);
   }
   ```

1. Create a plugin-specific custom property that users can set on their own.

   In your plugin documentation, let users know what custom properties you have created so they know how to customize your plugin.

   ```css
   :root {
     --fancy-image-border-width: 2px;
   }

   img.fancy-image {
     border-width: var(--fancy-image-border-width);
     border-style: solid;
     border-color: var(--theme-color);
     border-radius: var(--border-radius-m, 5px);
   }
   ```

   Users can now customize your plugin the same way they customize other docsify-themeable values:

   ```html
   <style>
     :root {
       --fancy-image-border-width: 4px;
     }
   </style>
   ```

   Keep in mind you can use other custom properties as fallbacks and define multiple fallback values. This allows you to prioritize your plugin's styles, then theme styles, then a static values where needed.

   ```css
   :root {
     --fancy-image-border-color: gray;
     --fancy-image-border-style: solid;
     --fancy-image-border-width: 2px;
   }

   img.fancy-image {
     border-width: var(--fancy-image-border-width, var(--blockquote-border-width));
     border-style: var(--fancy-image-border-style, solid);
     border-color: var(--fancy-image-border-color, var(--theme-color, purple));
     border-radius: var(--border-radius-m, 5px);
   }
   ```

There is one catch when using CSS custom properties: they are not supported by legacy browsers. Docsify-themeable includes a [ponyfill](https://www.npmjs.com/package/css-vars-ponyfill) that solves this problem, but docsify does not. There are ways to address this, but that's a separate discussion. We can get into that if it's an issue you need to solve.

It's not really possible to over all of the options for making a plugin "themeable". These are just a few approaches. FWIW, I've added this to my list of potential future blogs posts. Now I just need to build a blog... 😉 

Good luck, and let me know if there is anything else I can do to help.
